apiVersion: v1
kind: ConfigMap
metadata:
  name: gharuka-guru-config
  namespace: gharuka-guru
data:
  PINECONE_ENV: "us-west1-gcp"
  PINECONE_INDEX_NAME: "ghar-ka-guru-index"
  DATABASE_URL: "postgresql://postgres:$(DATABASE_PASSWORD)@postgresql:5432/gharkaguru"
